/*
 * Copyright 2015 Red Hat, Inc. and/or its affiliates.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
*/

package pt.ipp.isep.dei;

import pt.ipp.isep.dei.model.*;
import pt.ipp.isep.dei.math.*;

import function pt.ipp.isep.dei.view.UI.*;

query "Conclusions"
	$conclusion : Conclusion()
end

rule "setup"
	when
		not Evidence()
	then

	    //Ask the values
		//askValue(Evidence.RC, Units.Ω);
		//askValue(Evidence.RE, Units.Ω);
		//askValue(Evidence.RB, Units.Ω);
		//askValue(Evidence.VCE, Units.V);
		//askValue(Evidence.VBE, Units.V);
		//askValue(Evidence.VBB, Units.V);
		//askValue(Evidence.VCC, Units.V);
		//askValue(Evidence.IB, Units.A);
		//askValue(Evidence.IC, Units.A);
		//askValue(Evidence.BJT_GAIN, null);

		//Set application mode
		answer(Evidence.ENABLE_GUIDED_MODE, "yes");

		//Set params
		NumericValue nv_Vce_on = new NumericValue(0.7,Units.V,new Multiplier("Fundamental Unit", "","", 1));
        Evidence e_Vce_on = new Evidence(Evidence.VCE_ON, nv_Vce_on.getToHuman(), nv_Vce_on);

        //Set Hypothesis
        insert(new Hypothesis(Hypothesis.ZONE, Hypothesis.ZONE_ACTIVE));
        insert(new Hypothesis(Hypothesis.ZONE, Hypothesis.ZONE_CUT_OVER));
        insert(new Hypothesis(Hypothesis.ZONE, Hypothesis.ZONE_SATURATION));
end

rule "GM_R1: Enable Active Zone hypothesis"
	when
		eval(answer(Evidence.ENABLE_GUIDED_MODE, "yes"))
		$hypothesis : Hypothesis( description == Hypothesis.ZONE, value == Hypothesis.ZONE_CUT_OVER, status == Status.Proposed)
	then
		System.out.println("test cut over zone");
end

rule "GM_R2: Test Active Zone hypothesis"
	when
		eval(answer(Evidence.ENABLE_GUIDED_MODE, "yes"))
		Hypothesis( description == Hypothesis.ZONE, value == Hypothesis.ZONE_CUT_OVER, status == Status.Rejected)
		$hypothesis : Hypothesis( description == Hypothesis.ZONE, value == Hypothesis.ZONE_ACTIVE, status == Status.Proposed)
	then
		System.out.println("test active zone");
end

rule "GM_R3: Conclude its Saturation Zone"
	when
		eval(answer(Evidence.ENABLE_GUIDED_MODE, "yes"))
		Hypothesis( description == Hypothesis.ZONE, value == Hypothesis.ZONE_CUT_OVER, status == Status.Rejected)
		Hypothesis( description == Hypothesis.ZONE, value == Hypothesis.ZONE_ACTIVE, status == Status.Rejected)
	then
		System.out.println("conclude saturation zone");
end


rule "unknown"
	when
		not Conclusion()
	then
		Conclusion c = new Conclusion(Conclusion.UNKNOWN);
		insert(c);
end

query "evidence"(String ev, String v)
	e : Evidence( evidence == ev, value == v )
end

